# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 434c5de02a2c0b5d6e9dd61b9a2ec2ba445fefd3ca85adb858e3f5f472bc10b1e933e7db66a3017541bad0d1383b008694f451b96f47d2ce45013e9c68568c7b

test:
  secret_key_base: 45576c18f5ac7caaca0454a859ddfd9e8ca4a713c706b172ba3f21c058a50f7b8d48fa392c653bde6e5a1041dcf9e6037e85a5273c21d2c8b4039f9bc83ce019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
